#!/usr/bin/perl -T

use strict;

use LiteAPI;

use CGI;
use CGI::Carp qw(fatalsToBrowser);
use JSON;

use Scalar::Util qw(looks_like_number);

sub abort {
# exit is not supported in mod_perl
    goto DONE;
}

my $q = CGI->new;
my %p = $q->Vars;

my $t=LiteAPI::cache_ticker();

print $q->header('text/plain');

if ($t->{$p{currency}}) {
    if (!looks_like_number($p{value})) {
        print "Invalid Numerical Value\n";
    } else {
        my $rate=$t->{$p{currency}}->{sell};
        print $p{value}/$rate;
    }
} else {
    print "Unknown Currency Code\n";
}

